### ISSUE TITLE
Noticeable clicking when changing position values

### ISSUE THREAD

**Issue by thely** [Ircam-RnD/binauralFIR#10]
This may be obvious, but I've noticed a lot of clicking when altering position values while a single sound is playing, and it seems to be file-dependent. The breakbeat sample on the example page doesn't seem to suffer at all when the azimuth is altered, but other sounds I've tried it with (especially droney, pitched sounds) click a _lot_ when adjusted. I'm hoping to spatialize more than one source on a 2D plane, so I imagine if it's popping with one sound source, it'll be way worse with multiple sources.

Is there something I can do to minimize this? Is there a way to ramp JS values, in case the discretely jumping values are to blame?

**Comment by PyrApple** [comment]
Increasing the crossfade duration should solve your zipper noise issue. See setCrossfadeDuration() method in the [binauralFIR API](https://github.com/Ircam-RnD/binauralFIR#api).
